<meta charset="utf-8">
<#include "header.ftl">

<div class="main-div container">
	<div class="guest-div">
		<center><h1>${Session.hazi_cim}</h1></center>	
	</div>
	<div class="guest-div">
		<ul>
			<li>
				<h3>${Session.hazi_nyit}</h3>
				<p>${Session.hazi_nyitl}</p>
			</li>
			<li>
				<h3>${Session.hazi_eler}</h3>
				<p>${Session.hazi_elerl}</p>
			</li>
			<li>
				<h3>${Session.hazi_bej}</h3>
				<p>${Session.hazi_bejl}</p>
			</li>
			<li>
				<h3>${Session.hazi_kij}</h3>
				<p>${Session.hazi_kijl}</p>
			</li>
			<li>
				<h3>${Session.hazi_kulcs}</h3>
				<p>${Session.hazi_kulcsl}</p>
			</li>
			<li>
				<h3>${Session.hazi_fizetes}</h3>
				<p>${Session.hazi_fizetesl}</p>
			</li>
			<li>
				<h3>${Session.hazi_pot}</h3>
				<p>${Session.hazi_potl}</p>
			</li>
			<li>
				<h3>${Session.hazi_gyerek}</h3>
				<p>${Session.hazi_gyerekl}</p>
			</li>
			<li>
				<h3>${Session.hazi_dohany}</h3>
				<p>${Session.hazi_dohanyl}</p>
			</li>
			<li>
				<h3>${Session.hazi_internet}</h3>
				<p>${Session.hazi_internetl}</p>
			</li>
			<li>
				<h3>${Session.hazi_mini}</h3>
				<p>${Session.hazi_minil}</p>
			</li>
			<li>
				<h3>${Session.hazi_futes}</h3>
				<p>${Session.hazi_futesl}</p>
			</li>
			<li>
				<h3>${Session.hazi_takarit}</h3>
				<p>${Session.hazi_takaritl}</p>
			</li>
			<li>
				<h3>${Session.hazi_etterem}</h3>
				<p>${Session.hazi_ettereml}</p>
			</li>
			<li>
				<h3>${Session.hazi_hiba}</h3>
				<p>${Session.hazi_hibal}</p>
			</li>
			<li>
				<h3>${Session.hazi_allat}</h3>
				<p>${Session.hazi_allatl}</p>
			</li>
			<li>
				<h3>${Session.hazi_park}</h3>
				<p>${Session.hazi_parkl}</p>
			</li>
			<li>
				<h3>${Session.hazi_kar}</h3>
				<p>${Session.hazi_karl}</p>
			</li>
			<li>
				<h3>${Session.hazi_info}</h3>
				<p>${Session.hazi_infol}</p>
			</li>
		</ul>
	</div>
</div>

<#include "footer.ftl">